version: "3.8"
services:
  dev-postgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: echo
      POSTGRES_PASSWORD: echo
      POSTGRES_DB: echo
    restart: always
    networks:
      - lesson
networks:
  lesson: